services:
  - type: web
    name: redeco-frontend
    env: python
    region: ohio
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn frontend_redeco.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ENV
        value: production
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: redeco-frontend.onrender.com
